package dataMapper

import (
	"testing"

	cmp "github.com/google/go-cmp/cmp"
)

func TestIssueMapping(t *testing.T) {
	src := map[string]interface{}{
		"url":            "https://api.github.com/repos/Codertocat/Hello-World/issues/1",
		"repository_url": "https://api.github.com/repos/Codertocat/Hello-World",
		"labels_url":     "https://api.github.com/repos/Codertocat/Hello-World/issues/1/labels{/name}",
		"comments_url":   "https://api.github.com/repos/Codertocat/Hello-World/issues/1/comments",
		"events_url":     "https://api.github.com/repos/Codertocat/Hello-World/issues/1/events",
		"html_url":       "https://github.com/Codertocat/Hello-World/issues/1",
		"id":             444500041,
		"node_id":        "MDU6SXNzdWU0NDQ1MDAwNDE=",
		"number":         1,
		"title":          "Spelling error in the README file",
		"user": map[string]interface{}{
			"login":               "Codertocat",
			"id":                  21031067,
			"node_id":             "MDQ6VXNlcjIxMDMxMDY3",
			"avatar_url":          "https://avatars1.githubusercontent.com/u/21031067?v=4",
			"gravatar_id":         "",
			"url":                 "https://api.github.com/users/Codertocat",
			"html_url":            "https://github.com/Codertocat",
			"followers_url":       "https://api.github.com/users/Codertocat/followers",
			"following_url":       "https://api.github.com/users/Codertocat/following{/other_user}",
			"gists_url":           "https://api.github.com/users/Codertocat/gists{/gist_id}",
			"starred_url":         "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
			"subscriptions_url":   "https://api.github.com/users/Codertocat/subscriptions",
			"organizations_url":   "https://api.github.com/users/Codertocat/orgs",
			"repos_url":           "https://api.github.com/users/Codertocat/repos",
			"events_url":          "https://api.github.com/users/Codertocat/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Codertocat/received_events",
			"type":                "User",
			"site_admin":          false,
		},
		"labels": []map[string]interface{}{
			{
				"id":      1362934389,
				"node_id": "MDU6TGFiZWwxMzYyOTM0Mzg5",
				"url":     "https://api.github.com/repos/Codertocat/Hello-World/labels/bug",
				"name":    "bug",
				"color":   "d73a4a",
				"default": true,
			},
		},
		"state":  "open",
		"locked": false,
		"assignee": map[string]interface{}{
			"login":               "Codertocat",
			"id":                  21031067,
			"node_id":             "MDQ6VXNlcjIxMDMxMDY3",
			"avatar_url":          "https://avatars1.githubusercontent.com/u/21031067?v=4",
			"gravatar_id":         "",
			"url":                 "https://api.github.com/users/Codertocat",
			"html_url":            "https://github.com/Codertocat",
			"followers_url":       "https://api.github.com/users/Codertocat/followers",
			"following_url":       "https://api.github.com/users/Codertocat/following{/other_user}",
			"gists_url":           "https://api.github.com/users/Codertocat/gists{/gist_id}",
			"starred_url":         "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
			"subscriptions_url":   "https://api.github.com/users/Codertocat/subscriptions",
			"organizations_url":   "https://api.github.com/users/Codertocat/orgs",
			"repos_url":           "https://api.github.com/users/Codertocat/repos",
			"events_url":          "https://api.github.com/users/Codertocat/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Codertocat/received_events",
			"type":                "User",
			"site_admin":          false,
		},
		"assignees": []map[string]interface{}{
			{
				"login":               "Codertocat",
				"id":                  21031067,
				"node_id":             "MDQ6VXNlcjIxMDMxMDY3",
				"avatar_url":          "https://avatars1.githubusercontent.com/u/21031067?v=4",
				"gravatar_id":         "",
				"url":                 "https://api.github.com/users/Codertocat",
				"html_url":            "https://github.com/Codertocat",
				"followers_url":       "https://api.github.com/users/Codertocat/followers",
				"following_url":       "https://api.github.com/users/Codertocat/following{/other_user}",
				"gists_url":           "https://api.github.com/users/Codertocat/gists{/gist_id}",
				"starred_url":         "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
				"subscriptions_url":   "https://api.github.com/users/Codertocat/subscriptions",
				"organizations_url":   "https://api.github.com/users/Codertocat/orgs",
				"repos_url":           "https://api.github.com/users/Codertocat/repos",
				"events_url":          "https://api.github.com/users/Codertocat/events{/privacy}",
				"received_events_url": "https://api.github.com/users/Codertocat/received_events",
				"type":                "User",
				"site_admin":          false,
			},
		},
		"milestone": map[string]interface{}{
			"url":         "https://api.github.com/repos/Codertocat/Hello-World/milestones/1",
			"html_url":    "https://github.com/Codertocat/Hello-World/milestone/1",
			"labels_url":  "https://api.github.com/repos/Codertocat/Hello-World/milestones/1/labels",
			"id":          4317517,
			"node_id":     "MDk6TWlsZXN0b25lNDMxNzUxNw==",
			"number":      1,
			"title":       "v1.0",
			"description": "Add new space flight simulator",
			"creator": map[string]interface{}{
				"login":               "Codertocat",
				"id":                  21031067,
				"node_id":             "MDQ6VXNlcjIxMDMxMDY3",
				"avatar_url":          "https://avatars1.githubusercontent.com/u/21031067?v=4",
				"gravatar_id":         "",
				"url":                 "https://api.github.com/users/Codertocat",
				"html_url":            "https://github.com/Codertocat",
				"followers_url":       "https://api.github.com/users/Codertocat/followers",
				"following_url":       "https://api.github.com/users/Codertocat/following{/other_user}",
				"gists_url":           "https://api.github.com/users/Codertocat/gists{/gist_id}",
				"starred_url":         "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
				"subscriptions_url":   "https://api.github.com/users/Codertocat/subscriptions",
				"organizations_url":   "https://api.github.com/users/Codertocat/orgs",
				"repos_url":           "https://api.github.com/users/Codertocat/repos",
				"events_url":          "https://api.github.com/users/Codertocat/events{/privacy}",
				"received_events_url": "https://api.github.com/users/Codertocat/received_events",
				"type":                "User",
				"site_admin":          false,
			},
			"open_issues":   1,
			"closed_issues": 0,
			"state":         "closed",
			"created_at":    "2019-05-15T15:20:17Z",
			"updated_at":    "2019-05-15T15:20:18Z",
			"due_on":        "2019-05-23T07:00:00Z",
			"closed_at":     "2019-05-15T15:20:18Z",
		},
		"comments":           0,
		"created_at":         "2019-05-15T15:20:18Z",
		"updated_at":         "2019-05-15T15:20:18Z",
		"closed_at":          "2019-05-16T15:20:18Z",
		"author_association": "OWNER",
		"body":               "It looks like you accidently spelled 'commit' with two 't's.",
	}
	expected := map[string]interface{}{
		"assignees": []map[string]interface{}{
			{
				"avatarUrl":   "https://avatars1.githubusercontent.com/u/21031067?v=4",
				"id":          21031067,
				"isSiteAdmin": false,
				"login":       "Codertocat",
				"type":        "User",
				"url":         "https://github.com/Codertocat",
			},
		},
		"authorAssociation": "OWNER",
		"body":              "It looks like you accidently spelled 'commit' with two 't's.",
		"closedAt":          "2019-05-16T15:20:18Z",
		"createdAt":         "2019-05-15T15:20:18Z",
		"id":                444500041,
		"isLocked":          false,
		"labels": []map[string]interface{}{
			{
				"color":   "d73a4a",
				"default": true,
				"id":      1362934389,
				"name":    "bug",
				"node_id": "MDU6TGFiZWwxMzYyOTM0Mzg5",
				"url":     "https://api.github.com/repos/Codertocat/Hello-World/labels/bug",
			},
		},
		"milestone": map[string]interface{}{
			"closedAt":     "2019-05-15T15:20:18Z",
			"closedIssues": 0,
			"createdAt":    "2019-05-15T15:20:17Z",
			"creator": map[string]interface{}{
				"avatarUrl":   "https://avatars1.githubusercontent.com/u/21031067?v=4",
				"id":          21031067,
				"isSiteAdmin": false,
				"login":       "Codertocat",
				"type":        "User",
				"url":         "https://github.com/Codertocat",
			},
			"description": "Add new space flight simulator",
			"dueOn":       "2019-05-23T07:00:00Z",
			"url":         "https://github.com/Codertocat/Hello-World/milestone/1",
			"id":          4317517,
			"number":      1,
			"openIssues":  1,
			"state":       "closed",
			"title":       "v1.0",
			"updatedAt":   "2019-05-15T15:20:18Z",
		},
		"number":    1,
		"state":     "open",
		"title":     "Spelling error in the README file",
		"updatedAt": "2019-05-15T15:20:18Z",
		"url":       "https://github.com/Codertocat/Hello-World/issues/1",
		"user": map[string]interface{}{
			"avatarUrl":   "https://avatars1.githubusercontent.com/u/21031067?v=4",
			"id":          21031067,
			"isSiteAdmin": false,
			"login":       "Codertocat",
			"type":        "User",
			"url":         "https://github.com/Codertocat",
		},
	}

	dest := mapIssue(src)

	if diff := cmp.Diff(expected, dest); diff != "" {
		t.Errorf("Returned value did not match expected. Difference (-want +got):\n%s", diff)
	}
}
